name: Code Quality & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Type checking
      working-directory: ./frontend
      run: npm run type-check
      
    - name: Linting
      working-directory: ./frontend
      run: npm run lint
      
    - name: Format checking
      working-directory: ./frontend
      run: npm run format:check
      
    - name: Security audit
      working-directory: ./frontend
      run: npm audit --audit-level=moderate
      
    - name: Run tests
      working-directory: ./frontend
      run: npm test -- --watchAll=false --coverage
      
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        directory: ./frontend/coverage
        fail_ci_if_error: false